### ISSUE TITLE
Cannot import KITShibbolethLogin

### ISSUE THREAD

**Issue by x-zvf** [I-Al-Istannen/ilias-tests#1]
(Your commit in PFERD)[https://github.com/Garmelon/PFERD/commit/596b6a7] renamed the `KITShibbolethLogin` class in `PFERD`, which this project depends on.

Now, `ilias-tests --help` fails with:
```
Traceback (most recent call last):
  File "<REDACTED>/OSTut/grading/venv/bin/ilias-tests", line 5, in <module>
    from ilias_tests.__main__ import main
  File "<REDACTED>/OSTut/grading/venv/lib/python3.13/site-packages/ilias_tests/__main__.py", line 12, in <module>
    from .automation import slurp_tests_from_folder, add_test, ilias_glob_regex, slurp_grading_state, upload_grading_state
  File "<REDACTED>/OSTut/grading/venv/lib/python3.13/site-packages/ilias_tests/automation.py", line 9, in <module>
    from .ilias_action import IliasInteractor
  File "<REDACTED>/OSTut/grading/venv/lib/python3.13/site-packages/ilias_tests/ilias_action.py", line 19, in <module>
    from PFERD.crawl.ilias.kit_ilias_web_crawler import KitShibbolethLogin, KitIliasWebCrawler, _iorepeat
ImportError: cannot import name 'KitShibbolethLogin' from 'PFERD.crawl.ilias.kit_ilias_web_crawler' (<REDACTED>/OSTut/grading/venv/lib/python3.13/site-packages/PFERD/crawl/ilias/kit_ilias_web_crawler.py)
```

**Comment by I-Al-Istannen** [comment]
Thanks! The repo used a lock file pinned to 3.5 so it should have worked, but maybe you did not use uv :P Fixed on master :lady_beetle:
